variables:
  primary: magenta
  secondary: green
  tertiary: red
  special: yellow
  transparency: 20
  fontName: SFNS Display
  fontSize: 13
  font: "-*-System San Francisco Display-*-*-*-*-11-*-*-*-*-*-*-*"
plugins:
  parsers:
    - themer.parsers.SweylaColorParser
    - themer.parsers.WallhavenColorParser
    - themer.parsers.KmeansColorParser
    - themer.parsers.CachedColorParser
    - themer.parsers.unsplash.UnsplashColorParser
    - themer.parsers.vim.VimColorParser
    - themer.ColorParser
  activators:
    - themer.activators.wallfix.WallfixActivator
    - themer.activators.i3.I3Activator
      # - themer.activators.acyl.ACYLActivator
files:
  Xdefaults.tpl: Xdefaults
  index.tpl: index.html
  i3.tpl: i3.conf
  terminal.tpl: terminal.conf
